baseURL = 'https://stephlocke.info'
title = 'Steph Locke'
# theme = "slamp"
DefaultContentLanguage = "en"
languageCode = 'en-gb'
enableEmoji = "true"
enableInlineShortcodes = "true"
enableGitInfo = "true"

[params]
author = "Steph Locke"
sitename = "Steph Locke"
description = "Steph Locke's personal website"
fonts = "https://fonts.googleapis.com/css2?family=Zilla+Slab+Highlight&family=Zilla+Slab:ital,wght@0,400;0,700;1,400&display=swap"
logo = "icons/sl.png"
logoalt = "Steph Locke"
copyright = "Stephanie Locke"
cookieNotice = "🍪 This site does not use any cookies"
themeColor = "#009688"
social = [["Linkedin", "https://www.linkedin.com/in/stephanielocke", "linkedin"], ["Twitter", "https://twitter.com/theStephLocke", "twitter"]]
socialProfiles = ["https://twitter.com/theStephLocke","https://www.linkedin.com/in/stephanielocke"]
ampElements = [ "amp-install-serviceworker"]
scss = ["custom.scss"]
homepageActiveSections= ["/resume"]
homepageLatestSections= ["/blog","/otherblogs","/press","/publications"]
showcase = 3
[params.ogp]
image = "img/NHQlogoborderless.png"
description = "Steph Locke"

[params.twitter]
card = "player"
title = "Steph Locke"
site = "@theStephLocke"
description = "Steph's personal website"
image = "img/NHQlogoborderless.png"
image_alt = "Steph Locke"



[outputs]
home = ["HTML", "RSS", "REDIRECTS", "JSON", "WEBMANIFEST"]
page = [ "HTML" ]

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]
  [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""
[outputFormats.JSON]
mediaType = "application/json"
baseName = "feed"
path = "azureindex"
isPlainText =  true

[outputFormats.WEBMANIFEST]
mediaType = "application/manifest+json"
baseName = "manifest"
isPlainText =  true

[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[languages]
  [languages.en]
    weight = 1

[module]
  [[module.imports]]
    path = "github.com/stephlocke/slamp"
